title = "gitleaks config for gh-get-reviews"

[[rules]]
id = "GH_PAT"
description = "GitHub personal access token"
regex = '''ghp_[A-Za-z0-9_]{36,}'''
tags = ["token", "github"]

[[rules]]
id = "NPM_TOKEN"
description = "NPM token or npm auth token"
regex = '''(NPM_TOKEN|NODE_AUTH_TOKEN|npm_token)\s*=\s*[A-Za-z0-9_\-\.=]{20,}'''
tags = ["token", "npm"]

[[rules]]
id = "PRIVATE_KEY"
description = "Private key header (RSA PRIVATE KEY)"
regex = '''-----BEGIN (RSA |OPENSSH |EC |DSA )?PRIVATE KEY-----'''
tags = ["private-key", "pem"]

[[rules]]
id = "AWS_ACCESS_KEY_ID"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws"]

[[rules]]
id = "SLACK_WEBHOOK"
description = "Slack webhook URL"
regex = '''https?://hooks\.slack\.com/services/[A-Z0-9_/]+'''
tags = ["slack"]

# Allowlist example (to prevent false positives on known test fixtures)
[allowlist]
# paths = ["tests/fixtures/*"]


# Notes:
# - This is a compact personal-repo focused config. Adjust regex and allowlist for your project.
# - For production use, consider using the official gitleaks default rules + your additions.
